# Generated by Django 4.2.13 on 2024-05-19 08:24

import app.models.game
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='compiled_play',
            field=models.FileField(null=True, upload_to=app.models.game.user_directory_path, verbose_name='Compiled play'),
        ),
        migrations.AlterField(
            model_name='battle',
            name='status',
            field=models.IntegerField(choices=[('-1', 'Not Started'), ('0', 'Error'), ('1', 'Ok')], default='-1'),
        ),
        migrations.AlterField(
            model_name='game',
            name='play',
            field=models.FileField(max_length=1000, null=True, upload_to=app.models.game.user_directory_path, verbose_name='Play'),
        ),
    ]
